spring:
  application:
    name: hiresync
  datasource:
    url: jdbc:postgresql://localhost:5434/hiresync
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#      ddl-auto: none
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET_KEY}
app:
  resume:
    upload-dir: ${FILE_PATH}
  template-path: ${TEMPLATE_PATH}
  template-path-update: ${TEMPLATE_PATH_UPDATE}


#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
